name: Deploy Tomcat (Self-hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, ec2, tomcat]  # 上で付けたラベルに合わせる
    steps:
      - uses: actions/checkout@v4
      - name: Deploy locally on EC2
        run: /usr/local/bin/deploy_tomcat.sh
